import type { PortalKey } from '../types/rbac';

export const ROLE_PERMISSIONS: Record<PortalKey, string[]> = {
  admin: [
    'dashboard.view_full',
    'student.manage',
    'teacher.manage',
    'class.manage',
    'assignment.oversight',
    'attendance.view_all',
    'results.publish',
    'exam.manage',
    'hall_ticket.generate',
    'timetable.manage',
    'announcement.manage',
    'fee.manage',
    'report.view_all',
    'settings.global',
    'rbac.manage',
    'syllabus.manage',
    'notification.send_all',
    'chatbot.manage',
    'id_card.generate',
  ],
  teacher: [
    'dashboard.view_own_classes',
    'class.view_own',
    'assignment.create',
    'assignment.grade',
    'attendance.mark',
    'attendance.view_own_class',
    'results.enter',
    'timetable.view_own',
    'announcement.create',
    'report.view_class',
    'syllabus.edit_own',
    'notification.send_own_class',
    'chatbot.use',
    'settings.profile',
    'id_card.view',
  ],
  parent: [
    'dashboard.view_own_child',
    'student.view_own_child',
    'assignment.view_child',
    'attendance.view_child',
    'results.view_child',
    'timetable.view_child',
    'announcement.view',
    'fee.view_own',
    'report.view_child',
    'syllabus.view_child_class',
    'notification.receive',
    'chatbot.use',
    'settings.profile',
    'id_card.view_child',
  ],
  student: [
    'dashboard.view_own',
    'student.view_own',
    'assignment.view_own',
    'assignment.submit',
    'attendance.view_own',
    'results.view_own',
    'timetable.view_own',
    'announcement.view',
    'syllabus.view_own_class',
    'notification.receive',
    'chatbot.use',
    'settings.profile',
    'id_card.view_own',
    'hall_ticket.view_own',
  ],
};
